### ISSUE TITLE
Make this repository private?

### ISSUE THREAD

**Issue by johnousterhout** [VijayDaultani/Pintos-Project1-Mac#1]
I'm a Professor at Stanford, and I'm teaching an Operating Systems course that uses Pintos for its class projects. I'm writing because an automated search of GitHub identified this repository as possibly containing solutions for the Pintos programming projects. This is a problem for us, because it makes it very easy for students to cheat. Even if they just look at your solution, and don't copy it, that will still reduce the educational experience for them. If this repo does indeed contain Pintos solutions, would you be willing to take it down or at least make it private? If so, that would be a great help to us. If for some reason you absolutely must keep the repository public, it would still be a help if you could rename it so that it doesn't appear in searches for `Pintos`. Thanks for considering this request.

**Comment by vijaydaultani** [comment]
Respected Professor John,

I am really sorry, that this repository is causing problems for your course. Although I just started working on this repository some time back and then got busy in some other work, hence could not continue updating this repository for any of the assignments. So any of the students could not have seen any solutions from this repository. 

I would have definitely made this repository private on the first hand, but unfortunately I am not a paid member of github. So I have already changed the name of the repository to ProjectA-Mac, so that it will not have Pintos in its name now. I hope this can work for now. Once I become paid member of github I will make this repository Private.

You can let me know, in case you still have any concerns or if you want me to take down this repository.

Regards,
Vijay.

**Comment by johnousterhout** [comment]
Thanks; renaming the repository should solve the problem.
